# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabekole/ferda

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabekole/ferda

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabekole/ferda/CMakeFiles /home/gabekole/ferda//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabekole/ferda/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ferda

# Build rule for target.
Ferda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ferda
.PHONY : Ferda

# fast build rule for target.
Ferda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/build
.PHONY : Ferda/fast

hardware/Barometer.o: hardware/Barometer.cpp.o
.PHONY : hardware/Barometer.o

# target to build an object file
hardware/Barometer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/Barometer.cpp.o
.PHONY : hardware/Barometer.cpp.o

hardware/Barometer.i: hardware/Barometer.cpp.i
.PHONY : hardware/Barometer.i

# target to preprocess a source file
hardware/Barometer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/Barometer.cpp.i
.PHONY : hardware/Barometer.cpp.i

hardware/Barometer.s: hardware/Barometer.cpp.s
.PHONY : hardware/Barometer.s

# target to generate assembly for a file
hardware/Barometer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/Barometer.cpp.s
.PHONY : hardware/Barometer.cpp.s

hardware/IMU.o: hardware/IMU.cpp.o
.PHONY : hardware/IMU.o

# target to build an object file
hardware/IMU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/IMU.cpp.o
.PHONY : hardware/IMU.cpp.o

hardware/IMU.i: hardware/IMU.cpp.i
.PHONY : hardware/IMU.i

# target to preprocess a source file
hardware/IMU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/IMU.cpp.i
.PHONY : hardware/IMU.cpp.i

hardware/IMU.s: hardware/IMU.cpp.s
.PHONY : hardware/IMU.s

# target to generate assembly for a file
hardware/IMU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/IMU.cpp.s
.PHONY : hardware/IMU.cpp.s

hardware/Igniter.o: hardware/Igniter.cpp.o
.PHONY : hardware/Igniter.o

# target to build an object file
hardware/Igniter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/Igniter.cpp.o
.PHONY : hardware/Igniter.cpp.o

hardware/Igniter.i: hardware/Igniter.cpp.i
.PHONY : hardware/Igniter.i

# target to preprocess a source file
hardware/Igniter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/Igniter.cpp.i
.PHONY : hardware/Igniter.cpp.i

hardware/Igniter.s: hardware/Igniter.cpp.s
.PHONY : hardware/Igniter.s

# target to generate assembly for a file
hardware/Igniter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/Igniter.cpp.s
.PHONY : hardware/Igniter.cpp.s

hardware/RF.o: hardware/RF.cpp.o
.PHONY : hardware/RF.o

# target to build an object file
hardware/RF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/RF.cpp.o
.PHONY : hardware/RF.cpp.o

hardware/RF.i: hardware/RF.cpp.i
.PHONY : hardware/RF.i

# target to preprocess a source file
hardware/RF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/RF.cpp.i
.PHONY : hardware/RF.cpp.i

hardware/RF.s: hardware/RF.cpp.s
.PHONY : hardware/RF.s

# target to generate assembly for a file
hardware/RF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/RF.cpp.s
.PHONY : hardware/RF.cpp.s

hardware/TVC.o: hardware/TVC.cpp.o
.PHONY : hardware/TVC.o

# target to build an object file
hardware/TVC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/TVC.cpp.o
.PHONY : hardware/TVC.cpp.o

hardware/TVC.i: hardware/TVC.cpp.i
.PHONY : hardware/TVC.i

# target to preprocess a source file
hardware/TVC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/TVC.cpp.i
.PHONY : hardware/TVC.cpp.i

hardware/TVC.s: hardware/TVC.cpp.s
.PHONY : hardware/TVC.s

# target to generate assembly for a file
hardware/TVC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/hardware/TVC.cpp.s
.PHONY : hardware/TVC.cpp.s

src/Controller.o: src/Controller.cpp.o
.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i
.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s
.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Mode.o: src/Mode.cpp.o
.PHONY : src/Mode.o

# target to build an object file
src/Mode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Mode.cpp.o
.PHONY : src/Mode.cpp.o

src/Mode.i: src/Mode.cpp.i
.PHONY : src/Mode.i

# target to preprocess a source file
src/Mode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Mode.cpp.i
.PHONY : src/Mode.cpp.i

src/Mode.s: src/Mode.cpp.s
.PHONY : src/Mode.s

# target to generate assembly for a file
src/Mode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Mode.cpp.s
.PHONY : src/Mode.cpp.s

src/Navigation.o: src/Navigation.cpp.o
.PHONY : src/Navigation.o

# target to build an object file
src/Navigation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Navigation.cpp.o
.PHONY : src/Navigation.cpp.o

src/Navigation.i: src/Navigation.cpp.i
.PHONY : src/Navigation.i

# target to preprocess a source file
src/Navigation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Navigation.cpp.i
.PHONY : src/Navigation.cpp.i

src/Navigation.s: src/Navigation.cpp.s
.PHONY : src/Navigation.s

# target to generate assembly for a file
src/Navigation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Navigation.cpp.s
.PHONY : src/Navigation.cpp.s

src/Telemetry.o: src/Telemetry.cpp.o
.PHONY : src/Telemetry.o

# target to build an object file
src/Telemetry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Telemetry.cpp.o
.PHONY : src/Telemetry.cpp.o

src/Telemetry.i: src/Telemetry.cpp.i
.PHONY : src/Telemetry.i

# target to preprocess a source file
src/Telemetry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Telemetry.cpp.i
.PHONY : src/Telemetry.cpp.i

src/Telemetry.s: src/Telemetry.cpp.s
.PHONY : src/Telemetry.s

# target to generate assembly for a file
src/Telemetry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ferda.dir/build.make CMakeFiles/Ferda.dir/src/Telemetry.cpp.s
.PHONY : src/Telemetry.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Ferda"
	@echo "... hardware/Barometer.o"
	@echo "... hardware/Barometer.i"
	@echo "... hardware/Barometer.s"
	@echo "... hardware/IMU.o"
	@echo "... hardware/IMU.i"
	@echo "... hardware/IMU.s"
	@echo "... hardware/Igniter.o"
	@echo "... hardware/Igniter.i"
	@echo "... hardware/Igniter.s"
	@echo "... hardware/RF.o"
	@echo "... hardware/RF.i"
	@echo "... hardware/RF.s"
	@echo "... hardware/TVC.o"
	@echo "... hardware/TVC.i"
	@echo "... hardware/TVC.s"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Mode.o"
	@echo "... src/Mode.i"
	@echo "... src/Mode.s"
	@echo "... src/Navigation.o"
	@echo "... src/Navigation.i"
	@echo "... src/Navigation.s"
	@echo "... src/Telemetry.o"
	@echo "... src/Telemetry.i"
	@echo "... src/Telemetry.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

