name: C++ Unit Test

on:
  push:
    branches:
      - dev
      - unitTestPractice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ build environment
      uses: actions/setup-cpp@v2
      with:
        compiler: 'clang'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev

    - name: Build
      run: cmake . && make

    - name: Run tests
      run: ctest
