name: C++ Unit Test

on:
  push:
    branches:
      - dev
      - unitTestPractice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libeigen3-dev
        sudo apt-get install -y libgtest-dev
        sudo apt-get install pigpio

    - name: Build
      run: cmake . && make

    - name: Run tests
      run: ctest
